name: ci

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

defaults:
  run:
    shell: bash -l {0}

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}, OpenMM ${{ matrix.openmm }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12"]
        openmm: [true, false]

    steps:
    - uses: actions/checkout@v4

    - name: Install conda environment without OpenMM
      uses: mamba-org/setup-micromamba@v2
      with:
        environment-file: devtools/conda-envs/test_env.yaml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Optionally install OpenMM
      if: ${{ matrix.openmm == true }}
      run: micromamba install "openmm =8.1" -c conda-forge --yes

    - name: Install package
      run: python -m pip install -e .

    - name: Run mypy
      if: ${{ matrix.python-version == 3.10 }}
      run: mypy -p "openff.models"

    - name: Run tests
      run: python -m pytest -v -Werror --cov=openff/models --cov-report=xml --color=yes openff/models/

    - name: CodeCov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
